### PR TITLE
Issue329 node 12

### LINKED ISSUE #329: Upgrade Node.js 8 in admin
The admin interface uses Node.js v8 to compile. Node.js v8 is out of maintenance so should not be used anymore.

Please upgrade to Node.js v12 in the `admin/` folder.

### PR DESCRIPTION
**Pull request by jspaaks**
fixes #329

### CODE REVIEW

**Comment by jspaaks** [comment]
For some reason, the order of some elements has changed and as a result the admin tests on travis fail because some parts of the snapshots are different than what is being generated.

in part this could be due to some elements in the admin interface having been assigned an equal value for ``sortIndex``, e.g.

https://github.com/research-software-directory/research-software-directory/blob/5af4032d902c385c3b9ebcc33186749d5bcf5a03/admin/public/settings.json#L49-L65

This however does not explain the changed order of some of the other elements, e.g. the mentions Maybe related, when building the admin, I got a previously unseen error
```
warning sha.js@2.4.11: Invalid bin entry for "sha.js" (in "sha.js").
```

**Comment by jspaaks** [comment]
Related: https://github.com/research-software-directory/research-software-directory/issues/321

**Comment by sverhoeven** [comment]
The order must be due to the Node version iterating through the properties in a different way.

**Comment by sverhoeven** [comment]
Tried branch and was also able to use the admin interface

**Pull request merged**
