### PR TITLE
updated sample data with latest production data

### PR DESCRIPTION
**Pull request by jspaaks**
This PR updates the sample data to include the latest production data from research-software.nl

I found three problems with it while testing the migration scripts:

- ~~https://github.com/research-software-directory/research-software-directory/issues/679 (endDate and startDate in wrong format); PR #687~~ fixed
- ~~https://github.com/research-software-directory/research-software-directory/issues/680 (organization schema has property 'URL' that is not used) PR #689~~ closed without merge
- #676 (images as blobs) PR #696: merged

Other than these issues, the migration works correctly on the production data.

In order to test this PR, bring this branch up like normal, i.e.

1. clear the local state, including bind mounts in `docker-volumes`
1. &nbsp;
    ```
    docker-compose build 
    docker-compose up -d
    docker-compose logs --follow
    ```
1. Then, verify local installation using instructions from here https://github.com/research-software-directory/research-software-directory/blob/643-sample-data/docs/dev.md#verifying-the-local-installation
1. For admin, you should check there are no validation errors in any collection.

Note PRs #705 and #707 will likely also affect the shape of the sample data (not part of this PR though)

### CODE REVIEW

**Comment by jspaaks** [comment]
I updated the sample data and everything seems to work locally except I can't push the new data set (project_cache.bson is getting too large)

```
remote: warning: File database/db-init/project_cache.bson is 90.75 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: error: Trace: 3dfdaa7cf984eefd76803d92554518bf6e69ffc76d46ab68e28b3ec3773a737f
remote: error: See http://git.io/iEPt8g for more information.
remote: error: File database/db-init/project_cache.bson is 108.87 MB; this exceeds GitHub's file size limit of 100.00 MB
```

How do we feel about enabling git-lfs for bson files?

https://git-lfs.github.com/

**Comment by jspaaks** [comment]
Looks like I was able to solve the problem for now by preceding the commit (not the push) with

```
docker-compose exec database mongo rsd

# (in the mongo shell)
query = {}
update = {
    $set: {
        related.projects: []
    }
}

# make sure to not accidentally apply this next line to project collection
db.project_cache.updateMany(query, update)
```

**Comment by sverhoeven** [comment]
> I updated the sample data and everything seems to work locally except I can't push the new data set (project_cache.bson is getting too large)
> 
> ```
> remote: warning: File database/db-init/project_cache.bson is 90.75 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
> remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
> remote: error: Trace: 3dfdaa7cf984eefd76803d92554518bf6e69ffc76d46ab68e28b3ec3773a737f
> remote: error: See http://git.io/iEPt8g for more information.
> remote: error: File database/db-init/project_cache.bson is 108.87 MB; this exceeds GitHub's file size limit of 100.00 MB
> ```
> 
> How do we feel about enabling git-lfs for bson files? Looks like it may be less convenient for users, but the shortest path to success for us.
> 
> https://git-lfs.github.com/

I would remove the cache files and ask users to run `docker-compose exec harvesting python app.py resolve all`. With git lfs they will need to also do an extra step (installing git lfs) so why not use the machinery we already have.

**Review by cwmeijer — CHANGES_REQUESTED** [review]
I've checked all the links in the verification manual and clicked around a bit. All seems to work as expected except for http://localhost/oai-pmh?verb=ListRecords&metadataPrefix=datacite4 , which is giving me a 404.

image

Not sure if this is something you knew about or whether it has anything to do with this PR. So other than that, this PR seems fine to me.

**Comment by jspaaks** [comment]
> Not sure if this is something you knew about or whether it has anything to do with this PR. So other than that, this PR seems fine to me.

Is known and unrelated, can be fixed by running:

```
docker-compose exec harvesting python app.py harvest metadata
```

**Review by cwmeijer — APPROVED** [review]
w00t

**Pull request merged**
