### PR TITLE
692-update link checker ignore list

### PR DESCRIPTION
**Pull request by fdiblen**
# Pull request details

## List of related issues or pull requests

Refs: #692

## Describe the changes made in this pull request
Updates the link checker ignore list.

## Instructions to review the pull request
Verify if the link checker workflow checks https://github.com/research-software-directory/research-software-directory/blob/3.0.0/docs/dev.md#verifying-the-local-installation

### CODE REVIEW

**Comment by jspaaks** [comment]
Note this is for merging after the release, otherwise the link checker will fail

**Review by eriktks — APPROVED** [review]
```
git checkout remotes/origin/692-checker-link
docker run -e RUN_LOCAL=true -v \
   ${PWD}/data-migration/2.0-to-3.0/README.md:/tmp/lint/esciencecenter.md \
   github/super-linter 2>&1 | less
```

On my machine the linter does not complain about the removed address, neither before nor after using the PR, so that seems fine. But when an invalid url is added to the test file, the linter does not report it either. Does it actually check for invalid addresses?

**Review by sverhoeven — APPROVED** [review]
The release has been made so the link now works and no longer needs to be ignored
Please merge this PR.

**Comment by jspaaks** [comment]
https://github.com/research-software-directory/research-software-directory/pull/718#pullrequestreview-541987053

>  Does it actually check for invalid addresses?

No, but the [link checker does](https://github.com/research-software-directory/research-software-directory/blob/3.0.0/docs/dev.md#checking-if-theres-any-documentation-with-invalid-links).

**Comment by jspaaks** [comment]
Problem was fixed with PR #731, closing

**Pull request closed without merging**
