### PR TITLE
Smaller link icons 625

### PR DESCRIPTION
**Pull request by cwmeijer**
refs #625
Link icons in the sidebar of the project page should resemble the links in the mentions, but also the ones from the software pages wrt their size.

### CODE REVIEW

**Comment by cwmeijer** [comment]
Some checks are not successful. These seem to do with actual links that are broken. I don't think this has anything to do with the current PR, so I'm ignoring these checks for now.

**Comment by jspaaks** [comment]
> Some checks are not successful. These seem to do with actual links that are broken. I don't think this has anything to do with the current PR, so I'm ignoring these checks for now.

I sometimes rerun the checks when that happens by clicking the button on the right of the page, immediately above the terminal output here https://github.com/research-software-directory/research-software-directory/pull/626/checks?check_run_id=1384354722 . Looking at the failing links, it seems zenodo had a hiccup.

**Comment by cwmeijer** [comment]
Rerunning worked! Thanks!

**Review by sverhoeven — APPROVED** [review]
Looks good. 
Before
localhost_projects_764 (4)



After
localhost_projects_764 (5)

**Pull request merged**
