### PR TITLE
leiden logo

### PR DESCRIPTION
**Pull request by jspaaks**
Updated sample data with Leiden University logo with transparent background.

refs #566

### CODE REVIEW

**Comment by eriktks** [comment]
The update does not work for me. I keep seeing a logo with a white background on https://localhost/projects/764 even after removing the local state and reloading the image

**Comment by jspaaks** [comment]
@eriktks Can you clarify the steps you took for removing local state? Specifically, did you remove the `db` directory from docker-volumes?

**Review by fdiblen — APPROVED** [review]
The logo looks nice. Thanks @jspaaks :lollipop:

**Review by eriktks — APPROVED** [review]
Indeed, I had not removed docker_volumes/db/ . I have made a suggestion for making the instructions for the Removal of the local state more clear.

The update works and the image is transparent and looks fine.

**Pull request merged**
