### PR TITLE
Host graphs distro in reverse proxy as static files

### LINKED ISSUE #202: Host build of graphs in reverse-proxy
Now a python web server is used to hosts the /graphs, nginx is better equiped to hosts files so lets use the reverse-proxy to host these files. Similar to the admin site.

Doing development on the graphs/ dir should be possible by using a [proxy](https://facebook.github.io/create-react-app/docs/proxying-api-requests-in-development).

### PR DESCRIPTION
**Pull request by sverhoeven**
For graphs also switched from webpack based build system to vue cli.

Fixes #202

### CODE REVIEW

**Comment by sverhoeven** [comment]
@pushpanjalip could you look at the linting warnings?

**Comment by jspaaks** [comment]
@pushpanjalip. Can't find @sverhoeven ATM but here's what worked for me:
```
git clone https://github.com/research-software-directory/research-software-directory
git checkout static-graphs-202

# (I needed to update my node version, which was 
# admittedly old-- 8.9 or something. now using 10.15.1)

npm install

# I also installed vue-cli globally, but I don't think I used it in the end

# package.json defines a lint task
npm run lint
```

Good luck, let me know how you get on.

**Comment by jspaaks** [comment]
made the request above into an issue so it's blocking other developments https://github.com/research-software-directory/research-software-directory/issues/211

**Comment by pushpanjalip** [comment]
Fixed linting Errors Issue  and commited the code to static-graphs-202 branch.

**Pull request merged**
