### PR TITLE
add setting for building docker on windows

### PR DESCRIPTION
**Pull request by cwmeijer**
add windows specific setting to .env to streamline docker build there.

### CODE REVIEW

**Comment by jspaaks** [comment]
This doesn't work for me yet, can you please merge the commits from master into this? I'm guessing that will resolve my issue.

**Review by jspaaks — CHANGES_REQUESTED** [review]
Please merge commits from master into this, I'm getting #433 again.

**Comment by jspaaks** [comment]
For reference later, https://github.com/docker/compose/issues/4303

**Comment by cwmeijer** [comment]
Should be OK now. For me it works at least.

**Review by jspaaks — APPROVED** [review]
Yay it works!

**Pull request merged**
