### PR TITLE
650 project dates

### PR DESCRIPTION
**Pull request by eriktks**
# Pull request details

Fixes issue #650 

## List of related issues or pull requests

Refs: #650 

## Describe the changes made in this pull request

New code for adding project date from .csv file to .js file 

## Instructions to review the pull request

```
export PYTHONPATH=$PYTHONPATH:`pwd`/harvesting
export PYTHONPATH=$PYTHONPATH:`pwd`/data-migration
export PYTHONWARNINGS="ignore:Unverified HTTPS request"
python3 python3 data-migration/add_project_dates.py
```

Output is stored in the file `data-migration/add-project-dates`

<details><summary>log lines of a run</summary><pre>
project not found 27011301 eAstronomy
project not found 27011307 VLBPII/Green Genetics
project not found 27011310 eScience Technology
project not found 27013802 From sentiment to emotions
project not found 27014402 Visualising uncertainty and perspectives
project not found 27014501 A Lightpath for Optical Coherence Tomography imaging
project not found 27014502 Achieving Multidisciplinary High-Throughput
project not found 27014503 Recording history in large news streams
project not found 27014902 DAS-5
project not found 27017G07 Generalisatie ADAH
project not found 27017G15 Multiscale simulations of excitations dynamics
project not found 27017P01 Financial Network
project not found 27018601C EYRA Benchmark Platform Surf_NLeSC Alliance 2018
project not found 27019P01 Making Historical Biodiversity Data Available to Researchers
project not found 33013001 Flysafe 2
project not found 33013002 LifeWatch
project not found 33014001 ODEX4ALL - Open Discovery and Exchange for all
project not found 33015003 IndoDutch - Understanding Large Scale Human Mobility
project not found 33015006 Magnadata
project not found 33016001 Commit / valorisation call 2015-2016
project not found 33016002 The Riddle of Litery Quality
project not found 33016007 VLPB-AVE2
project not found 33017001 Part 2- Classifying activity types
project not found 33017003 Mediasuite
project not found 33017007 NWA Seed Money 17-02 Big Data
project not found 33017008 Extra consultancy: High spatial resolution phenological proj
project not found 33017009 Training Deep Learning applicaties
project not found 33017010 VWData
project not found 33017012 TTW Efficient deep learning EDL P16-25 project 4
project not found 33018003 MARIN Consultancy project
project not found 33018004 EliLilly
project not found 33018006 H2020 ReaxPro
project not found 33018008 Marin consultancy 2019
project not found 33020001 Primavera 2020
project not found 33020002 In-Silico Meat
project not found 33020003 ODISSEI
project not found 650001002 Expotree
project not found 650001003 Online Groups in organizations
project not found 650001005 Self Organizing Archives
39 projects were not found on RSD
unlinked project: MULTIXMAS
unlinked project: Deep learning OCR post-correction
unlinked project: 3D Geospatial Data Explor. for Modern Risk Management Systems
unlinked project: The Kumbh Mela Experiment
unlinked project: Beyond the Data Explosion
unlinked project: PROMIMOOC
unlinked project: eStep
unlinked project: Generic eScience Technologies
unlinked project: The Virtual Laboratory for Plant Breeding
unlinked project: Digital twins: monitoring ships’ state in real-time
unlinked project: Uncovering Networks of Corporate Control
unlinked project: FAIRifying eWaterCycle
unlinked project: ReaxPRO H2020
13 RSD projects were unlinked
</details>

Not all projects are found. The remaining 13 need to be updated manually. Note that the dates of the test project ABC-MUSE are changed by this script,

### CODE REVIEW

**Comment by eriktks** [comment]
Data file explanation:
1. project-dates.csv is the csv version of the .ods file provided by Jason (mail 20201118 11:25)
2. projects-zotero.csv is a list of project names and project numbers extracted from Zotero. Sometimes the project name on Zotero matches the one on the RSD when the corresponding name in Jason's file does not. The project number is then used to make a match.
3. add-project-dates.js is not visible in the data structure but it will be generated by the migration script. It will contain the links between the project slug and the project dates as requested in the issue

**Comment by jspaaks** [comment]
Hi Erik, thanks for making this PR. I still have to look at this in detail, but It seems you went a different route than what we discussed, and what the issue #650 calls for. Specifically, I expected this PR to have a file `data-migration/2.x-to-3.x/add-project-dates.js` with more `data` array elements than what is shown in https://github.com/research-software-directory/research-software-directory/blob/6cdcfc7fe829836fe806389179c58d22a565fecb/data-migration/2.x-to-3.x/add-project-dates.js. I didn't expect any python files or csv files.

Perhaps you have already seen this but the `add-project-dates.js` file I'm referrring to is part of pull request #645; its README (`data-migration/2.x-to-3.x/README.md`) documents how to use it to update the project start and end dates. Note that PR #645 is still under review at the moment, so keep an eye on any changes there that may affect this PR.

Perhaps there are valid reasons to abandon the plan outlined in #650 and PR #645; if so, the issue #650 is the appropriate place to make suggestions and discuss (preferably before you start coding). Additionally, our daily standup could be a venue to tell others that you think #650 should be implemented differently, which could then lead to further discussion one-on-one later on. I believe that this way, the team will be able to collaborate most effectively.

Thank you for your consideration!

**Comment by eriktks** [comment]
Yes, I am familiar with al the issues you refer to. I did not use the new directory structure of PR #645 because it is not available yet. We can wait with merging this PR #650 until #645 is merged so that this PR can use the required directory structure.

I can also trim this PR #650 down to only the output file of the migration script. But note that building the .js file from Jason's table is a non-trivial task because often the project titles in the table do not match the project titles in the RSD. The migration script in this PR increases the matches from 50% to 90%. That is why the script was added to the PR together with the required .csv input files.

**Review by jspaaks — APPROVED** [review]
Perfect, thanks for making these changes Erik!

**Pull request merged**
