### PR TITLE
Adds slug and contactperson to the schema

### PR DESCRIPTION
**Pull request by jspaaks**
Refs: #479, #497

This PR adds a required `slug` field to the schema. Also, members of the `team` array now have a property `isContactPerson` to be consistent with how things work on the software pages. I changed the minimum team size to 1 (because there is always at least a principal investigator).

1. ~~Still need to update the sample data~~
1. ~~`slug` still needs to be used by the frontend app~~ already worked out of the box due to https://github.com/research-software-directory/research-software-directory/blob/44477cfbd98f6f07961c87b45bde2ec9c4eb2602/backend/src/routes.py#L38 Thanks @Tommos0
1. ~~might need data migration update as well~~ added dummy value for `slug`; left `team` empty

To test, throw out local state including `./docker-volumes/db` directory. Then `build` and `up` the stack,
- check that http://localhost/projects/abc-muse resolves to ABC-MUSE's project page;
- for any other project, check that `http://localhost/api/project/<numeric id>` includes a key `slug` set to the value FIXME
- open any project through the admin interface, it should complain about
   - the value of `slug` (capitals are not allowed in the regex)
   - `team` should have at least one member but all project have team size zero
- check that http://localhost/projects/abc-muse shows Jason as the contact person

### CODE REVIEW

**Comment by jspaaks** [comment]
Should we unassign Faruk?

**Comment by sverhoeven** [comment]
I can take over from Faruk

**Comment by jspaaks** [comment]
I notified Faruk through Teams

**Review by sverhoeven — CHANGES_REQUESTED** [review]
* [x] The admin interface shows slug field
* [x] Slug and a single team member are now required in admin interface, was able to save when filled
* [x] https://localhost/projects/abc-muse works, with Jason as contact person

The links to a project on the projects/project/software pages still use the id, they should be using the slug. 
Can you update the templates?

**Comment by jspaaks** [comment]
> The links to a project on the projects/project/software pages still use the id, they should be using the slug.
Can you update the templates?

I would prefer to make an issue out of that, since we do not have valid slugs yet for all projects. Personally, I think it's fine to use ids though (but maybe the `/projects/<id>` route should redirect to `/projects/<slug>`, to facilitate meaningful copy-pasting from the browser's address bar). 

Let me know what you think!

**Review by sverhoeven — APPROVED** [review]
You are right projects should have unique slugs before fixing html pages created 
https://github.com/research-software-directory/research-software-directory/issues/627

**Comment by jspaaks** [comment]
Thanks for reviewing!

**Pull request merged**
