### PR TITLE
make organization.url optional property

### PR DESCRIPTION
**Pull request by jspaaks**
~~This PR removes unused property url from organization schema and updates the migration scripts~~

This PR retains unused property `url` from `organization` schema, but makes it optional. The migration script was also adapted to not include assigning a placeholder url anymore.

Refs: #680

To test, 

1. clear local state including docker bind mounts
1. `docker-compose build && docker-compose up -d && docker-compose logs`
1. check api, e.g. http://localhost/api/organization/commit should have string `url`
1. http://localhost/admin, click new organization

(TBC)

### CODE REVIEW

**Review by eriktks — CHANGES_REQUESTED** [review]
The schema change causes a problem for new organizations in de admin interface. The organization url is created as `undefined` but type checking for strings is still performed, presumably because of the `"type": "string"` definition in the schema. This results in the uri format check to fail which makes filling in the field non-optional.

**Comment by jspaaks** [comment]
I have the same behavior as what you describe, but as soon as I typed my new organization name, I was able to save. You?

**Comment by eriktks** [comment]
I had not noticed this but: yes I get the same behavior: when I update the name field the error message for the url field disappears.

**Comment by jspaaks** [comment]
After discussing with the team, we decided to close this, because it's not on the critical path to delivering our sprint goal (finalizing project index and project pages for all projects with up to date sample data). We can revisit this later, #680 remains open.

**Pull request closed without merging**
