### PR TITLE
updated the sample data; refs #498

### PR DESCRIPTION
**Pull request by jspaaks**
This PR adds updated sample data, specifically for project ABC-MUSE. 

Refs: #498

You can check if it works by:

1. [remove local state](https://github.com/research-software-directory/research-software-directory/blob/cfb86c3f193fcb750736016b9cb973e44953823d/docs/dev.md#removing-local-state)
1. &nbsp;
    ```shell
    docker-compose build
    docker-compose up -d
    docker-compose stop harvesting
    docker-compose logs --follow
    ```
1. [verify local installation](https://github.com/research-software-directory/research-software-directory/blob/cfb86c3f193fcb750736016b9cb973e44953823d/docs/dev.md#verifying-the-local-installation)
   - the link for the abc-muse project is in there (http://localhost://project/764)

### CODE REVIEW

**Review by sverhoeven — APPROVED** [review]
Visiting http://localhost//project/764 redirects to https://localhost/, I had to use https://localhost/projects/764 to get the ABC-muse project page.

Other projects like https://localhost/projects/1111 (ANDI) also render correctly and are editable.

That means I no longer need to run https://github.com/research-software-directory/research-software-directory/blob/master/data-migration/data-migration-2.0.x-to-2.1.x.js , that is great.

The snakemake output blog is not tied with project, but gives DNA image, so I am OK to keep it. Also impact seems picked from other projects, which may look strange when demo-ed, but is better than nothing.

Looking at https://localhost/projects/764 some data can be made more real 

* project website: http://www.amusecode.org/ as it explains core of muse.
* Add amuse project (810) to related projects
* Amuse/Omuse/Hymuse do not use any Xenon software, please remove Xenon* + sv-callers
* Use grpc4bmi (adaptor), MUSCLE 3 (alternative) and ESMValTool (downstream) as related software

I leave it up to you if want to make the project more real.

**Comment by jspaaks** [comment]
FYI I tried to mimic the mockup that Jason made, hence the blog, related software etc may seem odd.

> That means I no longer need to run https://github.com/research-software-directory/research-software-directory/blob/master/data-migration/data-migration-2.0.x-to-2.1.x.js , that is great.

That's good to know, but this should have been possible already since PR #454. Maybe I should have communicated this more explicitly / repeated some information.

http://localhost//project/764 was a typo, my apologies. Maybe we can adapt the routes later so both `project` and `projects` are valid.

**Comment by jspaaks** [comment]
Thanks for reviewing!

**Comment by jspaaks** [comment]
For reference, I made https://github.com/research-software-directory/research-software-directory/issues/530

**Pull request merged**
